<?
header("Content-type: text/html; charset=utf-8");
$lang = array(
	"global" => array(
		"login" 		=> "登入",
		"logout" 		=> "登出",
		"help"			=> "說明",
		"title"			=> "OX 部落閣",
		"keyword"		=> "OX 關鍵字",
		"desc" 			=> "OX 說明文字"
	),
	"index"  => array(
		"hot"				=> "哈燒文章",
		"board" 		=> "公告區塊",
		"category" 	=> "文章分類",
		"title"			=> "OX 部落閣",
		"keyword"		=> "OX 關鍵字",
		"desc" 			=> "OX 說明文字"
	),
	"member"	=> array(
		"sign_up"		=> "申請會員",
		"title"			=> "OX 部落閣-會員中心",
		"keyword"		=> "OX 關鍵字",
		"desc"			=> "OX 說明文字",
		"name"			=> "姓名",
		"birthday"	=> "生日",
		"bir_y"			=> "年",
		"bir_m"			=> "月",
		"bir_d"			=> "日",
		"account"		=> "帳號",
		"password"	=> "密碼",
		"email"			=> "信箱",
		"gcode"			=> "驗證碼",
		"confirm"		=> "我有詳細閱讀會員條款，瞭解和接受。",
		"submit"		=> "確定送出",
		"reset"			=> "重新填寫",
		"bot_desc"	=> "",
		"not_confirm"	=> "未認證"，
		"confirm_desc"	=> "認證說明",
		"confirm_area"	=> "會員認證專區",
	),
	"confirm"	=> array(
		"title"			=> "OX 部落閣-認證頁",
		"keyword"		=> "OX 關鍵字",
		"desc"			=> "OX 說明文字",
		"p_title"		=> "Email認證",
		"p_sub_title" => "認證聯絡信箱",
		"p_desc"		=> "我們將以此信箱與您聯絡，包含中獎訊息、郵寄密碼、會員重要訊息通知……等，請填寫您的常用信箱，並確認信箱可正常收信。提醒您，您必須先完成信箱認證，才能正常使用服務。"
		"change"		=> "變更信箱",
		"change_desc" => "若修改認證聯絡信箱，則需再重新認證。",
		"change_notice_title" => "注意： ",
		"change_notice_desc" => "由於各家信箱收信狀況不一，如收件匣未看到認證信，請先確認垃圾信件區，或稍等一段時間，目前原本可以使用的服務仍可繼續使用，自2012年3月起，未通過認證之帳號將無法繼續使用會員服務，不便之處敬請見諒！※即日起不再提供手機認證服務，原已使用手機認證之會員請重新使用 Email 認證 ※通過認證的 Email 可作為 PChome 服務登入及查詢密碼識別之使用(如該信箱同時認證多組帳號則不適用)",
	),
	
);
?>